apiVersion: v1
kind: Service
metadata:
  name: delivery-fulfillment
  labels:
    app: delivery-fulfillment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: delivery-fulfillment