name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./delivery-order/pom.xml
          mvn clean package -f ./delivery-fulfillment/pom.xml
          mvn clean package -f ./order-status/pom.xml
          mvn clean package -f ./payment-processing/pom.xml

      - name: Docker Build and push for DeliveryOrder
        uses: docker/build-push-action@v4
        with:
          context: ./delivery-order
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/delivery-order:latest
            ghcr.io/${{ github.repository }}/delivery-order:${{ github.ref_name }}
            
      - name: Docker Build and push for DeliveryFulfillment
        uses: docker/build-push-action@v4
        with:
          context: ./delivery-fulfillment
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/delivery-fulfillment:latest
            ghcr.io/${{ github.repository }}/delivery-fulfillment:${{ github.ref_name }}
            
      - name: Docker Build and push for OrderStatus
        uses: docker/build-push-action@v4
        with:
          context: ./order-status
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/order-status:latest
            ghcr.io/${{ github.repository }}/order-status:${{ github.ref_name }}
            
      - name: Docker Build and push for PaymentProcessing
        uses: docker/build-push-action@v4
        with:
          context: ./payment-processing
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/payment-processing:latest
            ghcr.io/${{ github.repository }}/payment-processing:${{ github.ref_name }}
            
