---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-order
  labels:
    app: delivery-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-order
  template:
    metadata:
      labels:
        app: delivery-order
    spec:
      containers:
        - name: delivery-order
          image: username/delivery-order:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-fulfillment
  labels:
    app: delivery-fulfillment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-fulfillment
  template:
    metadata:
      labels:
        app: delivery-fulfillment
    spec:
      containers:
        - name: delivery-fulfillment
          image: username/delivery-fulfillment:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-status
  labels:
    app: order-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-status
  template:
    metadata:
      labels:
        app: order-status
    spec:
      containers:
        - name: order-status
          image: username/order-status:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processing
  labels:
    app: payment-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-processing
  template:
    metadata:
      labels:
        app: payment-processing
    spec:
      containers:
        - name: payment-processing
          image: username/payment-processing:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: delivery-order
  labels:
    app: delivery-order
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: delivery-order


---


apiVersion: v1
kind: Service
metadata:
  name: delivery-fulfillment
  labels:
    app: delivery-fulfillment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: delivery-fulfillment


---


apiVersion: v1
kind: Service
metadata:
  name: order-status
  labels:
    app: order-status
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order-status


---


apiVersion: v1
kind: Service
metadata:
  name: payment-processing
  labels:
    app: payment-processing
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: payment-processing

